[build-system] # https://python-poetry.org/docs/pyproject/#poetry-and-pep-517
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry] # https://python-poetry.org/docs/pyproject/
name = "uglyrag"
version = "0.1.0"
description = ""
authors = ["uglyboy <uglyboy@uglyboy.cn>"]
readme = "README.md"
repository = "https://github.com/uglyboy-tl/UglyRAG"

[tool.poetry.dependencies] # https://python-poetry.org/docs/dependency-specification/
python = ">=3.11,<3.13"
appdirs = "^1.4.4"
sqlite-vec = "^0.1.6"
jieba-fast = {version="^0.53", extras = ["jieba"], optional=true}
fastembed = {version="^0.4.2", extras = ["fastembed"], optional=true}
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies] # https://python-poetry.org/docs/master/managing-dependencies/
ruff = "^0.8.1"

[tool.poetry.extras]
jieba = ["jieba-fast"]
fastembed = ["fastembed"]

[[tool.poetry.source]]
name = "my_mirror"
url = "https://mirrors.huaweicloud.com/repository/pypi/simple"
default = false
secondary = false

[tool.ruff]
fix = true
line-length = 120 # YOLO
src = ["src", "tests"]
target-version = "py311"

[tool.ruff.lint]
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "I", # isort
    "C", # flake8-comprehensions
    "B", # flake8-bugbear
]

ignore = [
    "E501", # line too long, handled by black
    "C901", # too complex
]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"